version: "3"

services:

  client:
    build:
      context: .
      dockerfile: ./core/Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/usr/src/app
    ports:
      - ${NX_PORT}:3000
    command: sh -c 'yarn && yarn dev'
    stdin_open: true

  api:
    build: ./api
    volumes:
      - ./api/:/usr/src/app
    ports:
      - ${PY_PORT}:8000
    tty: true

  db:
    image: mysql:8.0
    volumes:
      - db-store:/var/lib/mysql
      - ./db/conf/mysql.conf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - ${DB_PORT}:3306

  db_admin:
    container_name: phpMyAdmin
    image: phpmyadmin/phpmyadmin:latest
    volumes:
      - ./db/admin:/sessions
    environment:
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASS}
    links:
      - db
    ports:
      - ${DB_ADMIN_PORT}:80

volumes:
  db-store: